### ISSUE TITLE
Support ChromeGtkFrame

### ISSUE THREAD

**Issue by ericyan** [ericyan/numix#1]
Chrome/Chromium has a heuristics that tries to match the GTK theme; however it does not always pick the most appropriate colour.

That's why we need `ChromeGtkFrame`: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_gtk_theme_integration.md

**Comment by khurshid-alam** [comment]
Didn't chromium drop GTK instead of aura? Anyway feel free to create a pull request.

**Comment by ericyan** [comment]
Chromium still uses GTK+ for theme support. It's just that the main browser window is now rendered using Aura rather than being made up of GTK+ widgets.
